version: '3.7'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    ports:
      - 8000:8000
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://curas_admin@curass:tlo4413!E@curass.postgres.database.azure.com:5432/cura'