name: publish

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable

  testing:

    runs-on: ubuntu-latest
    needs: [linting]

    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Building Docker Image and run the test
        run: bash scripts/test.sh

  build-cura-image:
    runs-on: ubuntu-latest
    needs: [testing]


    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: Sigularusrex #${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Building and pushing cura image
      run: |
        cd backend
        docker build -t ghcr.io/sigularusrex/cura:latest .
        docker push ghcr.io/sigularusrex/cura:latest
